# Generated by Django 6.0 on 2025-12-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_offer_vehicle_remove_pricing_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
