# Generated by Django 6.0 on 2026-01-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_offer_discount_amount_offer_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='anonymous_token',
            field=models.CharField(blank=True, help_text='Token to identify anonymous inquiries before user login', max_length=100, null=True),
        ),
    ]
