# Generated by Django 6.0 on 2025-12-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_hotel_image_tourpackage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='places',
            field=models.TextField(blank=True, help_text='Comma-separated list of places to visit'),
        ),
    ]
