# Generated by Django 6.0 on 2025-12-30 18:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_destination_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cancelbooking',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='passengerdetail',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='cancellation',
        ),
        migrations.RemoveField(
            model_name='inclusionexclusion',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='review',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterModelOptions(
            name='custompackage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Custom Package', 'verbose_name_plural': 'Custom Packages'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name'], 'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name'], 'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inquiry', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-start_date'], 'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['start_month'], 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterModelOptions(
            name='tourpackage',
            options={'ordering': ['price_modifier'], 'verbose_name': 'Tour Package', 'verbose_name_plural': 'Tour Packages'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['name'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.RenameField(
            model_name='custompackage',
            old_name='user_contact',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='custompackage',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='custompackage',
            old_name='custom_destination',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='custompackage',
            old_name='no_of_people',
            new_name='participants_count',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='type',
            new_name='hotel_type',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='contact',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='date',
            new_name='inquiry_date',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='inquiry_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='season',
            name='months',
        ),
        migrations.RemoveField(
            model_name='season',
            name='tour',
        ),
        migrations.AddField(
            model_name='custompackage',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='budget_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='special_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('QUOTED', 'Quoted'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when this record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when this record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='star_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='admin_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when this record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed')], default='NEW', max_length=15),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when this record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AddField(
            model_name='season',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when this record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='season',
            name='end_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='season',
            name='start_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='additional_inclusions',
            field=models.JSONField(blank=True, default=list, help_text='Additional services included in this package'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='max_participants',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='package_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('LUXURY', 'Luxury')], default='STANDARD', max_length=10),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_modifier',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional cost over base tour price', max_digits=10),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when this record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='custompackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='custompackage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='custompackage',
            table='tours_custompackage',
        ),
        migrations.AlterModelTable(
            name='destination',
            table='tours_destination',
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='tours_hotel',
        ),
        migrations.AlterModelTable(
            name='inquiry',
            table='tours_inquiry',
        ),
        migrations.AlterModelTable(
            name='offer',
            table='tours_offer',
        ),
        migrations.AlterModelTable(
            name='season',
            table='tours_season',
        ),
        migrations.AlterModelTable(
            name='tourpackage',
            table='tours_tourpackage',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='tours_vehicle',
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_capacity', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='tours/images/')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of image URLs for tour gallery')),
                ('inclusions', models.JSONField(blank=True, default=list, help_text='List of included services')),
                ('exclusions', models.JSONField(blank=True, default=list, help_text='List of excluded services')),
                ('itinerary', models.JSONField(blank=True, default=list, help_text='Day-by-day tour schedule')),
                ('difficulty_level', models.CharField(choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('CHALLENGING', 'Challenging')], default='EASY', max_length=15)),
                ('category', models.CharField(choices=[('ADVENTURE', 'Adventure'), ('CULTURAL', 'Cultural'), ('RELAXATION', 'Relaxation'), ('BUSINESS', 'Business'), ('WILDLIFE', 'Wildlife'), ('SPIRITUAL', 'Spiritual')], default='CULTURAL', max_length=15)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.destination')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'db_table': 'tours_tour',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='applicable_tours',
            field=models.ManyToManyField(blank=True, related_name='offers', to='tours.tour'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='tours.tour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='tours.tour'),
        ),
        migrations.AlterUniqueTogether(
            name='tourpackage',
            unique_together={('tour', 'name')},
        ),
        migrations.CreateModel(
            name='TourItinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='tours.destination')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailed_itineraries', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Tour Itinerary',
                'verbose_name_plural': 'Tour Itineraries',
                'db_table': 'tours_touritinerary',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='TourPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_pricings', to='tours.season')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_pricings', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Tour Pricing',
                'verbose_name_plural': 'Tour Pricings',
                'db_table': 'tours_tourpricing',
            },
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='PassengerDetail',
        ),
        migrations.DeleteModel(
            name='CancelBooking',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.DeleteModel(
            name='InclusionExclusion',
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['destination'], name='tours_tour_destina_bbfad1_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['category'], name='tours_tour_categor_642bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['base_price'], name='tours_tour_base_pr_96cfee_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_active'], name='tours_tour_is_acti_e79caf_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['difficulty_level'], name='tours_tour_difficu_8c097b_idx'),
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='max_people',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='title',
        ),
        migrations.AlterUniqueTogether(
            name='tourpricing',
            unique_together={('tour', 'season')},
        ),
    ]
