# Generated by Django 6.0 on 2026-01-05 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_custompackage_customer'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tour',
            name='tours_tour_destina_bbfad1_idx',
        ),
        migrations.AddField(
            model_name='tour',
            name='destinations',
            field=models.ManyToManyField(help_text='Multiple destinations covered in this tour', related_name='tours', to='tours.destination'),
        ),
        migrations.AddField(
            model_name='tour',
            name='primary_destination',
            field=models.ForeignKey(blank=True, help_text='Main destination for this tour', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_tours', to='tours.destination'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Enter percentage value (e.g., 10 for 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['primary_destination'], name='tours_tour_primary_0519b4_idx'),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='destination',
        ),
    ]
