# Generated by Django 6.0 on 2026-01-05 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_populate_primary_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='primary_destination',
            field=models.ForeignKey(help_text='Main destination for this tour', on_delete=django.db.models.deletion.CASCADE, related_name='primary_tours', to='tours.destination'),
        ),
    ]
