# Generated by Django 6.0 on 2026-01-05 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_tour_primary_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='end_date',
            field=models.DateField(blank=True, help_text='Season end date (e.g., September 30, 2025)', null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='start_date',
            field=models.DateField(blank=True, help_text='Season start date (e.g., July 1, 2025)', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel_details',
            field=models.JSONField(blank=True, default=dict, help_text="Hotel details by destination: {destination_id: {hotel_name: 'Hotel Name', hotel_type: 'Type'}}"),
        ),
        migrations.AddField(
            model_name='tour',
            name='pricing_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed pricing: {season: {dates: [], two_sharing: 0, three_sharing: 0, child_price: 0}}'),
        ),
        migrations.AddField(
            model_name='tour',
            name='special_notes',
            field=models.TextField(blank=True, help_text='Special notes and conditions'),
        ),
        migrations.AddField(
            model_name='tour',
            name='vehicle_details',
            field=models.JSONField(blank=True, default=dict, help_text="Vehicle information: {type: 'AC INNOVA/XYLO', note: 'AC will not work in hill area'}"),
        ),
        migrations.AddField(
            model_name='tourpricing',
            name='available_dates',
            field=models.JSONField(default=list, help_text="List of specific available dates: ['10', '17', '24']"),
        ),
        migrations.AddField(
            model_name='tourpricing',
            name='child_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for child (4-11 years) without bed', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tourpricing',
            name='includes_return_air',
            field=models.BooleanField(default=True, help_text='Whether price includes return air travel'),
        ),
        migrations.AddField(
            model_name='tourpricing',
            name='three_sharing_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per person for 3-sharing accommodation', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tourpricing',
            name='two_sharing_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per person for 2-sharing accommodation', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tourpricing',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base price (usually same as two_sharing_price)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
