# Generated by Django 6.0 on 2026-01-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_contact_number_booking_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('REFUND_PENDING', 'Refund Pending'), ('CANCELLED_REFUNDED', 'Cancelled & Refunded'), ('CANCELLED_NOT_REFUNDED', 'Cancelled & Refund Rejected')], default='PENDING', max_length=50),
        ),
    ]
