# Generated by Django 6.0 on 2026-01-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='aadhar_card',
            field=models.ImageField(blank=True, help_text='Aadhar card image for identity verification', null=True, upload_to='bookings/aadhar/'),
        ),
    ]
