# Generated by Django 6.0 on 2026-01-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_aadhar_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='applied_offer_id',
            field=models.CharField(blank=True, help_text='ID of applied offer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount before discount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied', max_digits=12),
        ),
    ]
